languageCode = "en-us"
title = "Einu sinni รก Koala"
theme = "detox"
baseurl = "https://davityle.github.io/"
PygmentsStyle = "tango"

[params]
	description = "A software development blog by Tyler Davis"
	linkedin = "davityle"
	github = "davityle"
	email = "td@tyler-davis.com.com"
	google_analytics = "UA-59928738-2"
