languageCode = "en-us"
title = ""
theme = "hugo-uno"
baseurl = "http://davityle.github.io/blog/"
canonifyurls = true
uglyurls = true

[params]
	description = "a blog for anyone who cares"
	cover = "http://tylerdavis.info/images/entryx1600.jpg"
	AuthorName = "Tyler Davis"
	github = "davityle"
	email = "tyler@goodintheglobe.com"
