languageCode = "en-us"
title = "If You Care"
theme = "detox"
baseurl = "http://davityle.github.io/"

[params]
	description = "A software development blog by Tyler Davis"
	linkedin = "davityle"
	headerCover = "/images/fam-pic.jpg"
	github = "davityle"
	email = "tyler@goodintheglobe.com"
